[package]
name = "echo-leviathan941-flor"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
error-stack.workspace = true
flor.workspace = true
futures.workspace = true
log.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
